### ISSUE TITLE
Raising exceptions for api responses with status code > 200 ?

### ISSUE THREAD

**Issue by vancromp** [sphereio/sphere-php-sdk#115]
Hello,

I need some advice to correctly handle errors responses from api.
I'm wondering if it may be more convenient that the sdk throw an exception for each api response with status code > 200. Currently, all exceptions are re-packed to an object before returning from the sdk space. I see that there: https://github.com/sphereio/sphere-php-sdk/blob/master/src/Client/Adapter/Guzzle5Adapter.php#L59.
Can you explain me the strategy adopted ?

Thanks in advance, and sorry if a github issue is not the best place for such discussion.

Pierre

**Comment by ct-jensschulze** [comment]
Hey Pierre,

one of the reasons to introduce the wrapping to a response object to have the ability to check after an execution if it was successful without the need to always try/catch.

In the current development i wrapped all the exceptions to SDK specific ones and introduced also a switch to throw all exceptions

See also a169611bdb3879fe0f680c9580eeee364734724e

For a more direct communication about understanding and discussion you can also use support@sphere.io

Greetings

Jens

**Comment by nkuehn** [comment]
Hi Pierre. Sorry, this was tracked in two separate issues.  Now #97 is done. We have decided to leave the default to checks on  isError()  and getStatusCode()  on the response object (HTTP status codes).  But now you can setThrowExceptions(true) on the Config of the Client which switches behavior to Exceptions that map the HTTP status codes plus a bit more for our specific case.   
You'll have to decide early in your project because it affects the response handling code a lot : try/catch   vs.  if isError
